### ISSUE TITLE
Cannot use RdKafka class in symfony project

### ISSUE THREAD

**Issue by mohsenSy** [kozlice/monolog-kafka#2]
Hi,

I have a symfony project, I added monolog-kafka bundle to it and tried to use it like this:

```
use RdKafka\Conf;

$config = new RdKafka\Conf();
```

But I get this error:

`Attempted to load class "Conf" from namespace "test\TestBundle\Controller\RdKafka".
Did you forget a "use" statement for another namespace?`

How can I resolve it please?

**Comment by kozlice** [comment]
Hi @mohsenSy,

What version of [php-kafka](https://github.com/arnaud-lb/php-rdkafka) do you have installed?

**Comment by mohsenSy** [comment]
@kozlice 

It is version 3.0.4

![image](https://user-images.githubusercontent.com/11737155/32852896-1c4a7e52-ca42-11e7-892a-3e576ce849e6.png)

**Comment by kozlice** [comment]
@mohsenSy Sorry for being unresponsive, I didn't really have any time for OSS in past month. I've added tests for rdkafka 3.* and it seems to work fine.

You need either to import class:
```
use RdKafka\Conf;
$config = new Conf();
```
Or use FQDN:
```
$config = new \RdKafka\Conf();
```
But not both.
