### ISSUE TITLE
Update monolog to current version

### ISSUE THREAD

**Issue by chq81** [kozlice/monolog-kafka#3]
Hi,
is there any idea to update the monolog dependency to its latest version?
In form of tagging the current master?

Cheers
Christoph

**Comment by kozlice** [comment]
Hi @chq81,

Current dependency (`"^1.20.0"`) should allow everything below 2.0. I'll check, fix & update if it's not so.

**Comment by kozlice** [comment]
Clean installation successfully resolved into 1.24.0:
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 28 installs, 0 updates, 0 removals
  - Installing psr/log (1.1.0): Loading from cache
  - Installing monolog/monolog (1.24.0): Downloading (100%)
```
Since 1.24.0 is newest non-beta, I'm closing this one.

**Comment by chq81** [comment]
Hi there,
problem is that the you only provide the dependency "^1.20.0" in the master branch, it is not tagged yet.
Your latest tagged version is v1.0.0 which still holds the monolog dependency "~1.20.0", meaning it will not update to 1.24.0.
It would be nice if you could tag the current master version.

**Comment by kozlice** [comment]
@chq81 Sorry, I didn't realize that dependency was different between `master` and `v1.0.0`, thanks for pointing that out. Tagged current master as `v1.0.1`.
